[package]
name = "processor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_loader = { path = "../file_loader" }
bitflags = "1.2.1" # Used in amd64::interp
