[package]
name = "file_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
bytemuck = { version = "1.7.3", features = ["derive", "min_const_generics"] }
